default_mail: "default_mail"
smtp_address: "smtp"
mail_domain: "mail_domain"
mail_username: "username"
mail_password: "password"

development:
  host_name: "localhost:3000"
production:
  host_name: "hostname"